# Generated by Django 5.0.4 on 2024-05-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='image',
        ),
        migrations.AddField(
            model_name='usermember',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usermember',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
