# Generated by Django 5.0.4 on 2024-05-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0002_remove_usermember_age_remove_usermember_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
