# Generated by Django 5.0.4 on 2024-05-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0003_usermember_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='name',
        ),
    ]
