# Generated by Django 5.0.4 on 2024-05-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0005_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='website',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
