# Generated by Django 5.0.4 on 2024-05-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0006_alter_employee_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermember',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
