# Generated by Django 5.0.4 on 2024-05-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0007_employee_is_approved_usermember_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='companyname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
