# Generated by Django 5.0.4 on 2024-05-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0009_reset_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('companyname', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('job_schedule', models.CharField(max_length=255, null=True)),
                ('job_type', models.CharField(max_length=255, null=True)),
                ('job_des', models.CharField(max_length=255, null=True)),
                ('job_salary', models.IntegerField(null=True)),
                ('job_file', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
