# Generated by Django 5.0.4 on 2024-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0010_job_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='job_exp',
            field=models.IntegerField(null=True),
        ),
    ]
