# Generated by Django 5.0.4 on 2024-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0012_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
