# Generated by Django 5.0.4 on 2024-05-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0015_remove_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.AlterField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
