# Generated by Django 5.0.4 on 2024-05-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0016_remove_job_status_alter_job_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
