# Generated by Django 5.0.4 on 2024-06-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0017_alter_job_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_details',
            name='status',
        ),
    ]
