# Generated by Django 5.0.4 on 2024-06-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0018_remove_job_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
