# Generated by Django 5.0.4 on 2024-06-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0019_job_details_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_on',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
