# Generated by Django 5.0.4 on 2024-06-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0020_job_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_on',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
