# Generated by Django 5.0.4 on 2024-06-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0025_usermember_address_usermember_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='user_img',
        ),
    ]
