# Generated by Django 5.0.4 on 2024-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0029_job_details_user_alter_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='profile_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
