# Generated by Django 5.0.4 on 2024-06-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0031_employee_is_verified_usermember_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.employee'),
        ),
    ]
