# Generated by Django 5.0.4 on 2024-06-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0032_job_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_dob', to='jobportalapp.usermember'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_mobile', to='jobportalapp.usermember'),
        ),
    ]
