# Generated by Django 5.0.4 on 2024-06-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0035_applicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
