# Generated by Django 4.2.1 on 2024-07-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0040_remove_profile_dob_remove_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_dob', to='jobportalapp.usermember'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_mobile', to='jobportalapp.usermember'),
        ),
    ]
